### ISSUE TITLE
No way of providing suppressions.xml to checkstyle_config

### ISSUE THREAD

**Issue by thirtyseven** [bazel-contrib/rules_jvm#3]
Common usage of checkstyle involves defining errors to suppress in a separate file and including it like so:
```
<module name="SuppressionFilter">
        <property name="file" value="suppressions.xml"/>
</module>
```

However, such files will not be visible to any checkstyle_test targets due to sandboxing, resulting in an error like the following:
```
com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module SuppressionFilter - Unable to find: suppressions.xml
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:473)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:201)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:405)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:332)
	at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:191)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:126)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Unable to find: suppressions.xml
	at com.puppycrawl.tools.checkstyle.utils.CommonUtil.getResourceFromClassPath(CommonUtil.java:457)
	at com.puppycrawl.tools.checkstyle.utils.CommonUtil.getFilepathOrClasspathUri(CommonUtil.java:434)
	at com.puppycrawl.tools.checkstyle.utils.CommonUtil.getUriByFilename(CommonUtil.java:385)
	at com.puppycrawl.tools.checkstyle.filters.SuppressionsLoader.loadSuppressions(SuppressionsLoader.java:222)
	at com.puppycrawl.tools.checkstyle.filters.SuppressionFilter.finishLocalSetup(SuppressionFilter.java:274)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:197)
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:468)
	... 5 more
Checkstyle ends with 1 errors.
```

Worse, since `checkstyle_cli` does not check the exit code of checkstyle, and the string `ERROR` is not printed on stdout in the message above, any `checkstyle_test` that defines a suppression filter will pass without actually being linted.

Two possible changes to make here, let me know if a PR implementing them would be welcome:
1) Add a `data` parameter to `checkstyle_config` allowing extra files to be included in runfiles
2) Update the `checkstyle_cli` script to bubble up return code of checkstyle

**Comment by shs96c** [comment]
Being able to include arbitrary files using the `data` attribute makes sense, and I can't believe that we're not handling the return code properly 🤦!

A PR would be most welcome :) Thank you!

**Comment by shs96c** [comment]
@thirtyseven I'm back in the office and able to help if you'd like any support or guidance with the PR.

**Comment by thirtyseven** [comment]
Thanks @shs96c might have some cycles for it later this week

**Comment by shs96c** [comment]
That's great news :) I'm on the public [Bazel slack channel](https://slack.bazel.build/) and work UK hours if you need help or just want to chat about this PR.
