### ISSUE TITLE
If checkstyle file is named checkstyle.xml we fail

### ISSUE THREAD

**Issue by fzakaria** [bazel-contrib/rules_jvm#311]
I noticed this bug at https://github.com/bazel-contrib/rules_jvm/blob/50fec7933b7e5136a2c412b85990d024fce19698/java/private/checkstyle.bzl#L22

If the input file is also called `checkstyle.xml` this fails as it fails to write to the file it is reading from.

Additionally:
I've noticed that Bazel doesn't emit the junit.xml file created to STDOUT when errors are present.
Developers have complained having to `cat` the XML file individually locally.

I'm considering adding an `echo` to the test if there is a failure wdyt?

CC @vinnybod

**Comment by tjoneslo** [comment]
I too have run into this same problem of having check style fail with the stack trace 

```
Exception in thread "main" java.nio.file.FileSystemException: checkstyle.xml: Operation not permitted
  8   at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
  9   at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
 10   at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
 11   at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:261)
 12   at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:482)
 13   at java.base/java.nio.file.Files.newOutputStream(Files.java:228)
 14   at com.puppycrawl.tools.checkstyle.Main.getOutputStream(Main.java:522)
 15   at com.puppycrawl.tools.checkstyle.Main.createListener(Main.java:499)
 16   at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:407)
 17   at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:338)
 18   at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:195)
 19   at com.puppycrawl.tools.checkstyle.Main.main(Main.java:130)
```

**Comment by fzakaria** [comment]
Thanks for the fix @tjoneslo We also created a `StandardOutListener` so that you can see the results with `--test_output=streamed`

```java
/*
 * Copyright 2024 Confluent Inc.
 */
package checkstyle;

import com.puppycrawl.tools.checkstyle.AbstractAutomaticBean;
import com.puppycrawl.tools.checkstyle.AuditEventDefaultFormatter;
import com.puppycrawl.tools.checkstyle.AuditEventFormatter;
import com.puppycrawl.tools.checkstyle.api.AuditEvent;
import com.puppycrawl.tools.checkstyle.api.AuditListener;
import com.puppycrawl.tools.checkstyle.api.SeverityLevel;

import java.util.concurrent.locks.ReentrantLock;

/**
 * Very simple listener that prints audit events to standard out or error.
 * Non-configurable on purpose.
 */
public class StandardOutListener extends AbstractAutomaticBean implements AuditListener {

    private static final AuditEventFormatter FORMATTER = new AuditEventDefaultFormatter();
    private static final ReentrantLock STD_ERR_LOCK = new ReentrantLock();

    @Override
    protected void finishLocalSetup() {}

    @Override
    public void addError(AuditEvent event) {
        final SeverityLevel severityLevel = event.getSeverityLevel();
        if (severityLevel != SeverityLevel.IGNORE) {
            final String errorMessage = FORMATTER.format(copyOfForBazel(event));
            System.err.println(errorMessage);
        }
    }

    @Override
    public void addException(AuditEvent event, Throwable throwable) {
        STD_ERR_LOCK.lock();
        try {
            System.err.println(String.format("Error auditing: %s", stripBazelRunfileFromFileName(event.getFileName())));
            throwable.printStackTrace(System.err);
        } finally {
            STD_ERR_LOCK.unlock();
        }
    }

    @Override
    public void auditStarted(AuditEvent event) {
        System.out.println("Audit started");
    }

    @Override
    public void auditFinished(AuditEvent event) {
        System.out.println("Audit finished");
    }

    @Override
    public void fileStarted(AuditEvent event) {}

    @Override
    public void fileFinished(AuditEvent event) {
        System.out.flush();
    }

    /**
     * Let's prune the bazel-out junk at the start so we only see the filename.
     * We also prune out our local workspace name.
     */
    private static String stripBazelRunfileFromFileName(String fileName) {
        final String testSourceDirectory = System.getenv("TEST_SRCDIR");
        final String testWorkspace = System.getenv("TEST_WORKSPACE");
        return fileName.replace(testSourceDirectory, "").replace("/" + testWorkspace + "/", "");
    }

    /**
     * Create a copy of the event but apply @{link #stripBazelRunfileFromFileName}
     * to the filename.
     */
    private static AuditEvent copyOfForBazel(AuditEvent event) {
        final String fileName = event.getFileName();
        return new AuditEvent(event.getSource(), stripBazelRunfileFromFileName(fileName), event.getViolation());
    }
}
```

```
java_library(
    name = "StandardOutListener",
    srcs = ["StandardOutListener.java"],
    visibility = ["//visibility:public"],
    deps = [
        "@maven//:com_puppycrawl_tools_checkstyle",
    ],
)
```

```xml
<module name="Checker">
  <property name="localeLanguage" value="en"/>

  <module name="checkstyle.StandardOutListener">
  </module>
</module>
```
